Image gallery
ous8292/rx-goods-site pull request #8
Opened 2022-05-02 19:39 UTC by ous8292

2022-05-02 21:15 UTC, ous8292 commented
on commit 29c83cb having issues pulling API data correctly.

Getting an unsafe port error.

2022-05-02 21:17 UTC, ous8292 commented
Adding @cjmartian to review merges and make sure nothing breaks any further after restructuring the project

2022-05-02 21:20 UTC, ous8292 commented
Changed port value to a new port. Port originally used was a reserved port.

2022-05-03 16:26 UTC, cjmartian requested changes

2022-05-03 16:26 UTC, cjmartian commented on API/.env
> +API_KEY=552737677385964
Cycle your keys now, you should never commit credentials like this

2022-05-03 16:28 UTC, cjmartian commented
This is impossible to review. Over `350,000` changes on `2420` files. 

I think what's happened here is you've committed some files that aren't actually your code. Maybe some nodejs files or something. Either way, we should setup a `.gitignore` to not let this happen again. You should only ever commit your actual code; setup should be handled by whatever env manager you use.

2022-05-03 18:32 UTC, ous8292 commented
Closing pull request and retrying on branch `image-gallery-second-attempt`

2022-05-03 18:32 UTC, closed without merging